---
- name: Get ansible_user home directory
  shell: 'cat /etc/passwd "{{ ansible_ssh_user }}" | cut -d: -f6'
  register: ansible_home_result

- name: Set the fact for the other scripts to use
  set_fact: ansible_home='{{ansible_home_result.stdout}}'

- name: "Default : Make Directory BACKUP"
  file: path={{ BACKUP_DIR }} state=directory owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} mode=0755
  tags:
    - default

- name: "Default : Make Directory FILES"
  file: path={{ FILES_DIR }} state=directory owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} mode=0755
  tags:
    - default

- name: "Default : Make Directory RPMS"
  file: path={{ RPMS_DIR }} state=directory owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} mode=0755
  tags:
    - default

- name: "Default : Make Directory VER"
  file: path={{ DIFF_DIR }} state=directory owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} mode=0755
  tags:
    - default

- name: "Default : Make Directory DNSPERF"
  file: path={{ DNSPERF_DIR }} state=directory owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} mode=0755
  tags:
    - default

- name: "Default : Make Directory PACKAGES"
  file: path={{ PACKAGES_DIR }} state=directory owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} mode=0755
  tags:
    - default
